movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:mov>/', views.details, name='details')
]

vadly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResources

movie_resource = MovieResources()
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

api/models.py
from django.db import models
from movies.models import Movies
from tastypie.resources import ModelResource

# Create your models here.
class MovieResources(ModelResource):
    class Meta:
        queryset = Movies.objects.all()
        resource_name = 'movies'    
        excludes = ['created_at']    

movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Movies(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.shortcuts import render, get_object_or_404
from .models import Movies

# Create your views here.
def index(request):
    movies = Movies.objects.all()

    return render(request, 'movies/index.html', {
        'movies': movies
    })

def details(request, mov):
    movie = get_object_or_404(Movies, pk=mov)
    return render(request, 'movies/details.html', {
        'movie': movie
    })

movies/templates/movies/details.html
{% extends "base.html" %}

{% block title %}
    {{ movie.title }}
{% endblock  %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <h3>{{ movie.title }}</h3>
                <p>{{ movie.release_year }}</p>
                <p>{{ movie.daily_rate }}</p>
                <p>{{ movie.number_in_stock }}</p>
            </div>
        </div>
    </div>
{% endblock  %}

movies/templates/movies/index.html
{% extends "base.html" %}

{% block title %}
    Movies List
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h1 class="h1 text-center">Movies List</h1>

                <table class="table table-dark table-stripped">
                    <thead>
                        <tr>
                            <th>Movie Title</th>
                            <th>Release Year</th>
                            <th>Stock</th>
                            <th>Price</th>
                            <th>Genre</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for movie in movies %}
                            <tr>
                                <td><a href="{% url 'movies:details' movie.id %}">{{ movie.title }}</a></td>
                                <td>{{ movie.release_year }}</td>
                                <td>{{ movie.number_in_stock }}</td>
                                <td>{{ movie.daily_rate }}</td>
                                <td>{{ movie.genre }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock title %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    
</head>


<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'movies:index' %}">ARB Store</a>
          
            <ul class="navbar-nav">
              {% if user.is_authenticated %}
              
                <li class="nav-item">
                  <a href="#" class="nav-link text-uppercase">{{ user.username }}</a>
                </li>
              
              
              {% endif %} 
            </ul>
        </div>
      </nav>

      {% block content %}
      {% endblock content %}
      
</body>
</html>